image_width: 640
image_height: 480
camera_name: usb_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [525.0, 0.0, 319.5,
         0.0, 525.0, 239.5,
         0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [525.0, 0.0, 319.5, 0.0,
         0.0, 525.0, 239.5, 0.0,
         0.0, 0.0, 1.0, 0.0]


# image_width: 640
# image_height: 480
# camera_name: usb_cam
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [fx, 0, cx, 0, fy, cy, 0, 0, 1]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [k1, k2, t1, t2, k3]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [fx, 0, cx, 0, 0, fy, cy, 0, 0, 0, 1, 0]
