mesh_dir: ar4

# j1_limit_min: !degrees -170
# j2_limit_min: !degrees -42
# j3_limit_min: !degrees -89
# j4_limit_min: !degrees -165
# j5_limit_min: !degrees -105
# j6_limit_min: !degrees -155

j1_limit_min: !degrees -150
j2_limit_min: !degrees -47
j3_limit_min: !degrees -110
j4_limit_min: !degrees -177
j5_limit_min: !degrees -103
j6_limit_min: !degrees -167

# j1_limit_max: !degrees 170
# j2_limit_max: !degrees 90
# j3_limit_max: !degrees 52
# j4_limit_max: !degrees 165
# j5_limit_max: !degrees 105
# j6_limit_max: !degrees 155

j1_limit_max: !degrees 184
j2_limit_max: !degrees 120
j3_limit_max: !degrees 62
j4_limit_max: !degrees 161
j5_limit_max: !degrees 103
j6_limit_max: !degrees 170

l6_length: 0.03625
